### ISSUE TITLE
ライセンスを追加してください

### ISSUE THREAD

**Issue by tenten0213** [progre/template-vagrant#2]
forkしたリポジトリを仕事で利用しようと考えているのですが、ライセンスは何になるでしょうか？

**Comment by progre** [comment]
ご指摘ありがとうございます。
MITライセンスとします。

**Comment by tenten0213** [comment]
ありがとうございます。
![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)
